sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
  directories:
    - node_modules
before_install:
  - git config --global user.name "MangoIce"
  - git config --global user.email "raodunwei@163.com"
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
branches:
  only:
    - source # build source branch only
script:
  - hexo clean
  - hexo generate # generate static files
after_success:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GH_TOKEN@github.com/Mango-Ice/Mango-Ice.github.io.git master